name: Deploy to Tencent CloudBase

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to CloudBase
        uses: TencentCloudBase/cloudbase-action@v2
        with:
          secretId: ${{ secrets.TENCENTCLOUD_SECRETID }}
          secretKey: ${{ secrets.TENCENTCLOUD_SECRETKEY }}
          envId: lyh-life-3gaebvhg40d9b9e8
